### ISSUE TITLE
title text doesnt have padding 

### ISSUE THREAD

**Issue by andygrillo** [openeew/openeew-provisioner#18]
![image](https://user-images.githubusercontent.com/6279965/109404732-8282d180-792e-11eb-85c2-41479320ec7d.png)

**Comment by gdpelican** [comment]
So I'm 100% clear here, is this saying that the 'OpenEEW Sensors' text should have more space at the top to account for the menu bar?

**Comment by andygrillo** [comment]
sorry I just mean that the title 'Turn on your..' seems aligned along the left edge with no padding. Perhaps this is intentional ?
