### ISSUE TITLE
Layout change for Landing Page

### ISSUE THREAD

**Issue by andygrillo** [openeew/openeew-provisioner#23]
- Color: Use white logo
- Font: Sliiightly increase “Provision your sensor” font size
- Alignment: Left-align text and OpenEEW logo

<img width="1009" alt="Screen 1" src="https://user-images.githubusercontent.com/6279965/109988136-dabe2880-7ccc-11eb-9dab-53d59741a88a.png">

**Comment by leotj** [comment]
This issue should be closed since already implemented.

**Comment by johnwalicki** [comment]
Agreed @leotj - fixed via
https://github.com/openeew/openeew-provisioner/pull/31
